<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TaskTracker.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
    <PackageReference Include="Dapper" Version="2.1.35" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TaskTracker.Application\TaskTracker.Application.csproj" />
  </ItemGroup>
</Project>
